---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: https://jp.translink.com.au/api/stop/timetable/{{ stopid }}
polling_headers: ''
polling_body: ''
id: 233040
custom_fields:
- keyname: about
  name: Alister Scott
  field_type: author_bio
  category: travel,life
  description: Upcoming departures for stops in Queensland via the Translink API
  github_url: https://github.com/alisterscott/trmnl-translink
- keyname: stopid
  field_type: string
  name: Translink Stop ID
  description: You can find your closest Stop IDs using the <a class="underline" href="https://jp.translink.com.au/plan-your-journey/stops" target="_blank">Translink Stops & Stations Page</a> by clicking a stop and getting it from the URL.
  placeholder: central-station
  help_text: eg. 003749 or central-station
  default: central-station
- keyname: hidenextmins
  field_type: number
  placeholder: 15
  default: 15
  name: Hide Number of Minutes
  description: Hide departures for this number of minutes from refresh
  min: 0
  max: 60
  help_text: Min 0, Max 60 mins
name: Queensland Stop Timetable (Translink)
refresh_interval: 15
